name: Continuous integration

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Black
        run: black --check --config=pyproject.toml .

      - name: Run Ruff
        run: ruff check --config pyproject.toml .

      # - name: Run Mypy
      #   run: mypy --config-file=pyproject.toml .
      # TODO uncomment when python files

      # - name: Run unit-tests
      #   run: pytest --cov=<FOLDER> --cov-report term-missing --durations=5 --disable-warnings tests/
      # TODO uncomment when unit tests
