name: Continuous integration

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install explain
        run: pip install -e .

      - name: Run black
        run: black --check --config=pyproject.toml .

      - name: Run ruff
        run: ruff check --config pyproject.toml .

      - name: Run mypy
        run: mypy --config-file=pyproject.toml .

      - name: Run unit-tests
        run: pytest --cov=explain tests/
